// Constants for dropdowns
export const COMPANY_SIZES = [
  "0-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1000+",
];

export const INDUSTRIES = [
  "Agriculture",
  "Aerospace",
  "Automotive",
  "Biotech",
  "Construction",
  "Consulting",
  "E-commerce",
  "Education",
  "Energy",
  "Entertainment",
  "Finance",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Hospitality",
  "IT Services",
  "Insurance",
  "Legal",
  "Logistics",
  "Manufacturing",
  "Marketing",
  "Media",
  "Non-profit",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "Technology",
  "Telecommunications",
  "Transportation",
  "Other",
];
